version: "3.7"

services:
  ptpro-secure-module:
    image: fe-ptpro-secure
    build:
      context: .
      dockerfile: docker/dockerfile
    container_name: fe-ptpro-secure-module
    hostname: 'localhost'
    restart: "no"
    tty: true
    working_dir: /app
    environment:
      NG_CLI_ANALYTICS: "false"
    ports:
      - "4800:4800"
    volumes:
      - ./module:/usr/src/app/src/modules/secure
    #command: sh -c "/tmp/submodules.sh"
    networks:
      - app-network
      
  nginx-server:
    image: nginx:alpine
    container_name: nginx-server
    restart: "no"
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - 'angular-ui'
    networks:
      - app-network
#Docker networks
networks:
  app-network:
    driver: bridge